### ISSUE TITLE
Add Victoria Box & Southern red cedar tree to species.json

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#212]
ToDO: 

- add these 2 trees to the species.json
- check that the json is valid using a json validator (not make sure you add ',' after entry ID = 303

    {
        "COMMON": "Victorian Box",
        "TYPE": "broadleaf",
        "SCIENTIFIC": "Pittosporum undulatum",
        "ID": "304",
        "ITREECODE": "PIUN",
        "LEVEL": "medium",
        "ITREECODE_APPROX":"n"
        },

    {
        "COMMON": "Southern Redcedar",
        "TYPE": "conifer",
        "SCIENTIFIC": "Juniperus virginiana v. silicicola",
        "ID": "305",
        "ITREECODE": "JUSI",
        "LEVEL": "medium",
        "ITREECODE_APPROX":"n"
        }

**Comment by halmueller** [comment]
My personal JSON hack (also works for arrays/sets in Swift): leave a comma after the last entry. So in this case you'd add a comma after entry 303 (this time), and also add a comma after entry 305. The next time, just add 306 (also with an extra comma).

It makes the commits/code reviews cleaner, because the only lines that show up are the new entries.

**Comment by TreeMama** [comment]
added
![Screenshot_1624422536](https://user-images.githubusercontent.com/62637055/123039719-7e7c3300-d3a7-11eb-9867-34e5dfe7f3c6.png)
