### ISSUE TITLE
V2.1+ Upgrade ansi-regex

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#256]
ToDO:

Upgrade ansi-regex (in it's own feature branch - called 'ansi-regex-upgrade')

Once tested that nothing broke- push to /develop/
![Capture5](https://user-images.githubusercontent.com/62637055/141661753-ca57c396-f3e2-416b-b6e9-3312253d0aad.JPG)

**Comment by andaniel2029** [comment]
Normally, We can use the npm (node package manager) command to upgrade the project or fix security vulnerabilities in the dependencies list.

In order to find potential vulnerabilities in the repo.

we can use the **npm audit** command.

It will generate the report.

`61 vulnerabilities (13 low, 47 moderate, 1 high)
`

![image](https://user-images.githubusercontent.com/51064752/142722059-19feaad9-7633-45c4-85bd-3a22e8542e2b.png)


Also, the Github security policy can also notify you.


The solution is to use **npm update** or **npm audit fix --force** command for such problem:

https://docs.npmjs.com/cli/v8/commands/npm-update

But in our case, the project is mixed with react native expo and CLI version.

So even if we update the dependencies using the above commands, we will get other errors during the build.

Let's see "ansi-regex" dependency, for example.

![image](https://user-images.githubusercontent.com/51064752/142719007-dfd641c2-7939-411c-a673-c8211191bcb7.png)

This dependency relates to other many dependencies as well.


BTW, I upgraded some dependencies versions and got build success on my machine with Android phone.

I am not sure, It is solved or not, I think It can be checked by the repo owner.

https://github.com/TreeMama/iSeaTree-React-Prototype/tree/ansi-regex-upgrade

Please check this repo.
