### ISSUE TITLE
V2.1+ get a config file (like envVariables.ts) able to switch between the two firebase dbs (dev and prod)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#259]
As of our react-native upgrade - we have been unable to test against dev. It looks like the config file doesn't work anymore (envVariables.ts). We need to fix this issue immediately.

**Comment by andaniel2029** [comment]
I checked this issue on my Android phone.

The **envVariables.ts** file contains web app config information (dev firebase) now.

![image](https://user-images.githubusercontent.com/51064752/142894645-74730e5d-2033-45aa-97a9-aeb841adcb57.png)

Actually, the **envVariables.ts** file doesn't work for the prod/dev database switch.

As you know, we have prod and dev projects in firebase.

For react native android and ios, we need to make an app there to get config information.

- Android
![image](https://user-images.githubusercontent.com/51064752/142895079-53ee5536-9b46-43be-9332-526f9c75bf0a.png)

- IOS
![image](https://user-images.githubusercontent.com/51064752/142895187-d9c439ed-ee2b-4d9f-8f66-85f95f0e6ff9.png)

The problem is, we are using the prod's database Android and iOS config information now.

That's why we are getting data in the prod's DB when the users do some actions like register, login, and calculation, etc.

So We need to switch those config files when we build the release/production app for Android and IOS.


PS: when we switch the config file, we need to clean the project build.

- Android

**cd android
gradlew clean
cd ..
yarn android --deviceId=123456**


And I added console log information in App.tsx file.

![image](https://user-images.githubusercontent.com/51064752/142895998-a762613a-55b1-4568-a976-2e25742cc5c1.png)

![image](https://user-images.githubusercontent.com/51064752/142896240-b3070429-d627-41b1-b6fa-1ecc5bcbd6a9.png)
