### ISSUE TITLE
V2.1(patch) Add more badges for the number of trees

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#62]
Originally at V1 launch we only had 1, 5, 10. 

need to add 20...50...100..200.

**Comment by TreeMama** [comment]
@prasanna-dhamodaran

**Comment by TreeMama** [comment]
the badges can be found here:

https://drive.google.com/drive/u/1/folders/1Is_-AiMV9ItKrnf7IrNA7uABWeGL3bkg

**Comment by ryanflynndev** [comment]
Added 20, 50, 100 and 200 tree badges today. Tested the 20 tree badge and it worked. I am assuming the other three badges work, but we are holding off testing that for now. This is because the first test caused a lot of usage in Firebase. So we need to make sure that when we test these that we are under the quota for the free plan.
