### ISSUE TITLE
V2 - Buttons/Nav not displaying properly on newer iPhones (with no home button)

### ISSUE THREAD

**Issue by jyang81** [TreeMama/iSeaTree-React-Prototype#81]
Button and Nav text is being cut off on iPhones with a higher resolution. Might need to just adjust the font size on higher resolution displays.

![IMG_0442](https://user-images.githubusercontent.com/44694525/99888505-396e0380-2c02-11eb-9ab3-cf0f67dbd518.jpg)

**Comment by jyang81** [comment]
Possible suggestion:
https://stackoverflow.com/questions/33628677/react-native-responsive-font-size

**Comment by halmueller** [comment]
I'm not thrilled with the approach in that SO article. If phone's owner has increased the default text size, it's probably because they need it to be larger. So our layout has to respect that.

Responsive text size is a fundamental accessibility issue, right up there with red/green color blindness. The last stat I saw was that something over 40% of iPhone users have set a non-default text size.

**Comment by JonathanKoerber** [comment]
Is the text cut off on the rest of the navigation buttons as well?

**Comment by jyang81** [comment]
I'm not able to test this as I don't have the right iphone (the picture is not mine), but I assume the other nav text gets cut off as well. I'm also new to mobile dev, but is there a way to make the button size responsive to the content within them?

**Comment by TreeMama** [comment]
@jyang81 my neighbor has this phone - and was doing the release testing (where we saw this). I could probably contact her to test fixes. 

@JonathanKoerber yeah the text looked cut off on the nav buttons as well. 

If you want to change the icon width / height ...and the font sizes I could test.

**Comment by JonathanKoerber** [comment]
Sounds great, I'll get to it over the weed end.

**Comment by ryanflynndev** [comment]
Tested the app on an Iphone 11, and both the clear button and "add new" button look great.
